### ISSUE TITLE
massive error after fresh install

### ISSUE THREAD

**Issue by BinarySoul** [alex-rodriguez/easy_captcha_solver#3]
---------------------------------------------------------
code:
---------------------------------------------------------
`require 'rubygems'
require 'mechanize'
require 'open-uri'
require 'http-cookie'
require 'easy_captcha_solver'

easy_c = EasyCaptchaSolver.new(image_url: "http://www.madrid.org/infi_pub/html/web/CargarCaptchaAccion.icm?idCaptcha=")
easy_c.captcha
puts easy_c`

---------------------------------------------------------
error:
---------------------------------------------------------

> voidbyte@VoidCore ~/Ruby $ ruby downloader.rb 
/var/lib/gems/2.3.0/gems/ffi-inline-0.0.4.3/lib/ffi/inline/compilers/gcc.rb:35:in `compile': compile error: see logs at /tmp/.ffi-inline-1000/d38a60d0384f111d054925698c053d563c192fce.log (CompilationError)
	from /var/lib/gems/2.3.0/gems/ffi-inline-0.0.4.3/lib/ffi/inline/builders/c.rb:114:in `shared_object'
	from /var/lib/gems/2.3.0/gems/ffi-inline-0.0.4.3/lib/ffi/inline/builders.rb:90:in `block in build'
	from /var/lib/gems/2.3.0/gems/ffi-inline-0.0.4.3/lib/ffi/inline/builders.rb:87:in `instance_eval'
	from /var/lib/gems/2.3.0/gems/ffi-inline-0.0.4.3/lib/ffi/inline/builders.rb:87:in `build'
	from /var/lib/gems/2.3.0/gems/ffi-inline-0.0.4.3/lib/ffi/inline/inline.rb:54:in `singleton_inline'
	from /var/lib/gems/2.3.0/gems/ffi-inline-0.0.4.3/lib/ffi/inline/inline.rb:39:in `inline'
	from /var/lib/gems/2.3.0/gems/tesseract-ocr-0.1.8/lib/tesseract/c.rb:34:in `<module:C>'
	from /var/lib/gems/2.3.0/gems/tesseract-ocr-0.1.8/lib/tesseract/c.rb:31:in `<module:Tesseract>'
	from /var/lib/gems/2.3.0/gems/tesseract-ocr-0.1.8/lib/tesseract/c.rb:29:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/tesseract-ocr-0.1.8/lib/tesseract/api.rb:26:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/tesseract-ocr-0.1.8/lib/tesseract-ocr.rb:35:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/easy_captcha_solver-1.0.0/lib/easy_captcha_solver.rb:2:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from downloader.rb:5:in `<main>'

---------------------------------------------------------
Logfile:
---------------------------------------------------------

`
g++ -shared -fPIC    -o /tmp/.ffi-inline-1000/d38a60d0384f111d054925698c053d563c192fce.so /tmp/.ffi-inline-1000/d38a60d0384f111d054925698c053d563c192fce.cpp -ltesseract 2>>/tmp/.ffi-inline-1000/d38a60d0384f111d054925698c053d563c192fce.log
/tmp/.ffi-inline-1000/d38a60d0384f111d054925698c053d563c192fce.cpp:1:30: fatal error: tesseract/strngs.h: Datei oder Verzeichnis nicht gefunden
compilation terminated.
`

**Comment by theendcomplete** [comment]
I have the same error 
Any solution?
